### ISSUE TITLE
Sync existing users error LDAP import - &#38 - bool given

### ISSUE THREAD

**Issue by Tols78** [cconard96/glpi#444]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.6

### Bug description

Hello, 

Since i change user DN for connect to LDAP 

Synchronization of existing users via  search filter: KO
Synchronization In console mode via glpi:ldap:synchronize_users KO
Test connection ldap : OK

In graphical mode the LDAP filter is transformed 

`(&` (samaccountname=*) `(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))))`

Becomes 
`(&#38;` (samaccountname=*) `(&#38;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))))`

### Relevant log output
php-errors.log

```shell
[2023-02-13 18:10:02] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: ldap_parse_result(): Argument #2 ($result) must be of type LDAP\Result, bool given in C:\glpi\src\AuthLDAP.php at line 1868
	Ligne 1799:   front\ldap.import.php:69                           AuthLDAP::searchUser()
	Ligne 1801: [2023-02-13 18:10:02] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Something went wrong searching in LDAP directory in C:\glpi\src\AuthLDAP.php at line 3395
```

### Steps To reproduce

 Just go to the In graphical mode LDAP filter

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.6 ( => C:\glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT 
PHP 8.1.10 
Setup: max_execution_time="300" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="200M" 
Software: Microsoft-IIS
Server Software: mariadb.org binary distribution
	

	

### Anything else?

_No response_ #

**Comment by Tols78** [comment]
I am not an expert in PHP coding, I try we never know, it really blocks us in the implementation of our GLPI instance which worked well in 10.0.0.5 THKS

**Comment by Tols78** [comment]
I don't know too much about GitHub so I hope I posted in the right place :)

**Comment by Nol-go** [comment]
It's not on the right Project, this is not the main you should repost it on https://github.com/glpi-project/glpi

**Comment by Tols78** [comment]
I post to the right place : https://github.com/glpi-project/glpi/issues/14075
Thks
